# Generated by Django 5.2.3 on 2025-06-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
