# Generated by Django 5.2.3 on 2025-07-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_comentariocontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='alumno',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
