# Generated by Django 5.2.3 on 2025-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_archivos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivos',
        ),
    ]
